#define DEPARTURES_SCHEDULED    0
#define DEPARTURES_PERFORMED    1
#define PAYLOAD                 2
#define SEATS                   3
#define PASSENGERS              4
#define FREIGHT                 5
#define MAIL                    6
#define DISTANCE                7
#define RAMP_TO_RAMP            8
#define AIR_TIME                9
#define UNIQUE_CARRIER          10
#define AIRLINE_ID              11
#define UNIQUE_CARRIER_NAME     12
#define UNIQUE_CARRIER_ENTITY   13
#define REGION                  14
#define CARRIER                 15
#define CARRIER_NAME            16
#define CARRIER_GROUP           17
#define CARRIER_GROUP_NEW       18
#define ORIGIN_AIRPORT_ID       19
#define ORIGIN_AIRPORT_SEQ_ID   20
#define ORIGIN_CITY_MARKET_ID   21
#define ORIGIN                  22
#define ORIGIN_CITY_NAME        23
#define ORIGIN_STATE_ABR        24
#define ORIGIN_STATE_FIPS       25
#define ORIGIN_STATE_NM         26
#define ORIGIN_COUNTRY          27
#define ORIGIN_COUNTRY_NAME     28
#define ORIGIN_WAC              29
#define DEST_AIRPORT_ID         30
#define DEST_AIRPORT_SEQ_ID     31
#define DEST_CITY_MARKET_ID     32
#define DEST                    33
#define DEST_CITY_NAME          34
#define DEST_STATE_ABR          35
#define DEST_STATE_FIPS         36
#define DEST_STATE_NM           37
#define DEST_COUNTRY            38
#define DEST_COUNTRY_NAME       39
#define DEST_WAC                40
#define AIRCRAFT_GROUP          41
#define AIRCRAFT_TYPE           42
#define AIRCRAFT_CONFIG         43
#define YEAR                    44
#define QUARTER                 45
#define MONTH 			            46
#define DISTANCE_GROUP          47
#define CLASS                   48
#define DATA_SOURCE             49
